mysql:
  user:
  password:
  host:
  database: smash_that_cert
  question_table: exams_questions
  exam_list_table: exams_list

query:
  ingest_question_query: "REPLACE INTO {table_name}(exam_name, question_number, question_text, question_options,most_voted, link) VALUES('{exam_name}',{question_number},'{question_text}','{question_options}','{most_voted}', '{link}')"
  read_questions_query: >
    SELECT exam_name, question_number, question_text, question_options, most_voted, link
    FROM {table_name}
    WHERE most_voted != '-1' AND TRIM(exam_name) = '{exam_name}'
    ORDER BY question_number
  create_question_table_query: >
    CREATE TABLE smash_that_cert.exams_questions (
        exam_name varchar(255),
        question_number int,
        question_text text,
    	question_options text,
    	most_voted varchar(10),
        link varchar(500),
    	ingestion_dt DATETIME DEFAULT CURRENT_TIMESTAMP,
    	PRIMARY KEY (exam_name, question_number, link)
    );
  create_exam_list_table: >
    DROP TABLE IF EXISTS {dest_database}.{dest_table_name};
    CREATE TABLE {dest_database}.{dest_table_name} AS (
      SELECT exam_name, count(*) AS total_num_questions
      FROM {source_database}.{source_table_name}
      WHERE most_voted != '-1'
      GROUP BY exam_name
    );
  get_exam_list_query: >
    SELECT exam_name, total_num_questions
    FROM {database}.{table_name}
    ORDER BY exam_name
